openapi: 3.0.0
info:
  title: User Service API
  version: 1.0.0
  description: User service API specification
servers:
  - url: http://localhost:8081
    description: Local development server
paths:
  /:
    $ref: "paths/health.yaml"
  /api/v1/users/{id}:
    $ref: "paths/user.yaml"
components:
  schemas:
    UserResponse:
      $ref: "components/schemas/user.yaml#/UserResponse"
    UserData:
      $ref: "components/schemas/user.yaml#/UserData"
    ErrorResponse:
      $ref: "components/schemas/error.yaml#/ErrorResponse"
