// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateUser implements createUser operation.
	//
	// Register user (proxy to user service).
	//
	// POST /api/v1/users
	CreateUser(ctx context.Context, req *CreateUserRequest) (CreateUserRes, error)
	// Echo implements echo operation.
	//
	// Echo message with Pokemon info.
	//
	// POST /api/v1/echo
	Echo(ctx context.Context, req *EchoRequest) (EchoRes, error)
	// GetUser implements getUser operation.
	//
	// Get user by ID (proxy to user service).
	//
	// GET /api/v1/users/{id}
	GetUser(ctx context.Context, params GetUserParams) (GetUserRes, error)
	// HealthCheck implements healthCheck operation.
	//
	// Health check.
	//
	// GET /health
	HealthCheck(ctx context.Context) (HealthCheckOK, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
