// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"io"
)

type EchoBadRequest ErrorResponse

func (*EchoBadRequest) echoRes() {}

// Ref: #/EchoData
type EchoData struct {
	// Echoed message.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *EchoData) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *EchoData) SetMessage(val string) {
	s.Message = val
}

type EchoInternalServerError ErrorResponse

func (*EchoInternalServerError) echoRes() {}

// Ref: #/EchoRequest
type EchoRequest struct {
	// Message to echo.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *EchoRequest) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *EchoRequest) SetMessage(val string) {
	s.Message = val
}

// Ref: #/EchoResponse
type EchoResponse struct {
	Echo    EchoData    `json:"echo"`
	Pokemon PokemonData `json:"pokemon"`
}

// GetEcho returns the value of Echo.
func (s *EchoResponse) GetEcho() EchoData {
	return s.Echo
}

// GetPokemon returns the value of Pokemon.
func (s *EchoResponse) GetPokemon() PokemonData {
	return s.Pokemon
}

// SetEcho sets the value of Echo.
func (s *EchoResponse) SetEcho(val EchoData) {
	s.Echo = val
}

// SetPokemon sets the value of Pokemon.
func (s *EchoResponse) SetPokemon(val PokemonData) {
	s.Pokemon = val
}

func (*EchoResponse) echoRes() {}

// Ref: #/ErrorResponse
type ErrorResponse struct {
	// Error message.
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val string) {
	s.Error = val
}

type HealthCheckOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s HealthCheckOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// Ref: #/PokemonData
type PokemonData struct {
	// Pokemon ID.
	ID int `json:"id"`
	// Pokemon name.
	Name string `json:"name"`
	// Pokemon types.
	Types []TypeData `json:"types"`
	// Pokemon sprite URL.
	Sprite string `json:"sprite"`
}

// GetID returns the value of ID.
func (s *PokemonData) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *PokemonData) GetName() string {
	return s.Name
}

// GetTypes returns the value of Types.
func (s *PokemonData) GetTypes() []TypeData {
	return s.Types
}

// GetSprite returns the value of Sprite.
func (s *PokemonData) GetSprite() string {
	return s.Sprite
}

// SetID sets the value of ID.
func (s *PokemonData) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *PokemonData) SetName(val string) {
	s.Name = val
}

// SetTypes sets the value of Types.
func (s *PokemonData) SetTypes(val []TypeData) {
	s.Types = val
}

// SetSprite sets the value of Sprite.
func (s *PokemonData) SetSprite(val string) {
	s.Sprite = val
}

// Ref: #/TypeData
type TypeData struct {
	// Type slot number.
	Slot int `json:"slot"`
	// Type name.
	Name string `json:"name"`
}

// GetSlot returns the value of Slot.
func (s *TypeData) GetSlot() int {
	return s.Slot
}

// GetName returns the value of Name.
func (s *TypeData) GetName() string {
	return s.Name
}

// SetSlot sets the value of Slot.
func (s *TypeData) SetSlot(val int) {
	s.Slot = val
}

// SetName sets the value of Name.
func (s *TypeData) SetName(val string) {
	s.Name = val
}
