// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Echo implements echo operation.
//
// Echo message with Pokemon info.
//
// POST /echo
func (UnimplementedHandler) Echo(ctx context.Context, req *EchoRequest) (r EchoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// HealthCheck implements healthCheck operation.
//
// Health check.
//
// GET /
func (UnimplementedHandler) HealthCheck(ctx context.Context) (r HealthCheckOK, _ error) {
	return r, ht.ErrNotImplemented
}
