// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name)
VALUES ($1, $2)
RETURNING id, email, name
`

type CreateUserParams struct {
	Email string
	Name  string
}

type CreateUserRow struct {
	ID    pgtype.UUID
	Email string
	Name  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.Name)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID    pgtype.UUID
	Email string
	Name  string
}

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(&i.ID, &i.Email, &i.Name)
	return i, err
}
