// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetUser implements getUser operation.
	//
	// Get user by ID.
	//
	// GET /api/v1/users/{id}
	GetUser(ctx context.Context, params GetUserParams) (GetUserRes, error)
	// HealthCheck implements healthCheck operation.
	//
	// Health check.
	//
	// GET /
	HealthCheck(ctx context.Context) (HealthCheckOK, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
