// Code generated by ogen, DO NOT EDIT.

package ogen

// OperationName is the ogen operation name
type OperationName = string

const (
	GetUserOperation     OperationName = "GetUser"
	HealthCheckOperation OperationName = "HealthCheck"
)
