// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"io"
)

type CreateUserBadRequest ErrorResponse

func (*CreateUserBadRequest) createUserRes() {}

type CreateUserConflict ErrorResponse

func (*CreateUserConflict) createUserRes() {}

type CreateUserInternalServerError ErrorResponse

func (*CreateUserInternalServerError) createUserRes() {}

// Ref: #/CreateUserRequest
type CreateUserRequest struct {
	// User name.
	Name string `json:"name"`
	// User email address.
	Email string `json:"email"`
}

// GetName returns the value of Name.
func (s *CreateUserRequest) GetName() string {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *CreateUserRequest) GetEmail() string {
	return s.Email
}

// SetName sets the value of Name.
func (s *CreateUserRequest) SetName(val string) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *CreateUserRequest) SetEmail(val string) {
	s.Email = val
}

// Ref: #/ErrorResponse
type ErrorResponse struct {
	// Error message.
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val string) {
	s.Error = val
}

type GetUserInternalServerError ErrorResponse

func (*GetUserInternalServerError) getUserRes() {}

type GetUserNotFound ErrorResponse

func (*GetUserNotFound) getUserRes() {}

type HealthCheckOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s HealthCheckOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// Ref: #/UserData
type UserData struct {
	// User ID.
	ID string `json:"id"`
	// User name.
	Name string `json:"name"`
	// User email address.
	Email string `json:"email"`
}

// GetID returns the value of ID.
func (s *UserData) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *UserData) GetName() string {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *UserData) GetEmail() string {
	return s.Email
}

// SetID sets the value of ID.
func (s *UserData) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *UserData) SetName(val string) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *UserData) SetEmail(val string) {
	s.Email = val
}

// Ref: #/UserResponse
type UserResponse struct {
	User UserData `json:"user"`
}

// GetUser returns the value of User.
func (s *UserResponse) GetUser() UserData {
	return s.User
}

// SetUser sets the value of User.
func (s *UserResponse) SetUser(val UserData) {
	s.User = val
}

func (*UserResponse) createUserRes() {}
func (*UserResponse) getUserRes()    {}
