// Code generated by MockGen. DO NOT EDIT.
// Source: src/domain/gateway-interfaces/pokemon/gateway.go
//
// Generated by this command:
//
//	mockgen -source=src/domain/gateway-interfaces/pokemon/gateway.go -destination=test/mocks/pokemon_gateway_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pokemon "github.com/sukuname4976/portfolio/apis/bff/src/domain/entities/pokemon"
	pokemonid "github.com/sukuname4976/portfolio/apis/bff/src/domain/value-objects/pokemonid"
	gomock "go.uber.org/mock/gomock"
)

// MockGateway is a mock of Gateway interface.
type MockGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayMockRecorder
	isgomock struct{}
}

// MockGatewayMockRecorder is the mock recorder for MockGateway.
type MockGatewayMockRecorder struct {
	mock *MockGateway
}

// NewMockGateway creates a new mock instance.
func NewMockGateway(ctrl *gomock.Controller) *MockGateway {
	mock := &MockGateway{ctrl: ctrl}
	mock.recorder = &MockGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGateway) EXPECT() *MockGatewayMockRecorder {
	return m.recorder
}

// FetchByID mocks base method.
func (m *MockGateway) FetchByID(ctx context.Context, id pokemonid.PokemonID) (*pokemon.Pokemon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByID", ctx, id)
	ret0, _ := ret[0].(*pokemon.Pokemon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByID indicates an expected call of FetchByID.
func (mr *MockGatewayMockRecorder) FetchByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByID", reflect.TypeOf((*MockGateway)(nil).FetchByID), ctx, id)
}
